### ISSUE TITLE
how to get token?

### ISSUE THREAD

**Issue by dfp521** [schulzefelix/laravel-search-console#13]
$sites = SearchConsole::setAccessToken($token)->listSites();
how to get $token

**Comment by schulzefelix** [comment]
Hi,

the Access Token is the token you get after you authenticate your Google project to access the users data. Because the OAuth authentication can be used to access all different Google products its not included in that package and you need to provide that before.
Here a link to the basics fpr that:
https://developers.google.com/webmaster-tools/search-console-api-original/v3/how-tos/authorizing#OAuth2Authorizing

**Comment by hofmannsven** [comment]
The [Google OAuth 2.0 Playground](https://developers.google.com/oauthplayground/) is a helpful place to get started.
