### ISSUE TITLE
It is said searchType is deprecated. Does this affect  to the pacakge?

### ISSUE THREAD

**Issue by iamprageeth** [schulzefelix/laravel-search-console#35]
Refer : https://developers.google.com/webmaster-tools/v1/searchanalytics/query.

Thanks for this amazing  laravel package! 
Just wanted to know  this before starting a new project.

**Comment by schulzefelix** [comment]
Hey, thanks for pointing out and I definitely will change it, but not sure exactly when I have the time in the next weeks.

Since there is no one complaining so far, i guess the deprecated searchType is still working at the moment.

**Comment by iamprageeth** [comment]
You're welcome ! I think It is better  to close the issue only  after the update.

**Comment by iamprageeth** [comment]
Hi @schulzefelix  ! , Just checking back again. Wondering whether you had time to look into this ! . Actually to get discover and googlenews type results we have to send the "type" parameter I think. can you suggest me where I should do this change in my fork? 

Thanks

**Comment by schulzefelix** [comment]
Hey, thanks for the ping and I actually looked into this. As it turns out it seems the whole package needs a complete rewrite because the underlaying Google API changed, I hope mostly just the naming from Webmaster to SearchConsole and new functions, but we will know along the way.

There is no simply way in this state to replace searchType with type, since the new type parameter isn't in the old classes.
Thats the new ones I need to reference everywhere: https://github.com/googleapis/google-api-php-client-services/tree/main/src/SearchConsole
